apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: value
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
        - name: config
          configMap:
            name: redis
            items:
              - key: redisConfig
                path: redis.conf
      containers:
      - name: redis
        image: redis:7
        command:
          - "redis-server"
          - "/redis-master/redis.conf"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: "/data"
            name: redis-storage
          - mountPath: "/redis-master"
            name: config
